 $(document).ready(function(){
  $("#flip").click(function(){
    $(".panel").slideToggle("slow");
  });
});
$(document).ready(function(){
$("#about").click(function(){
    $("#us").slideToggle("slow");
});
});
$(document).ready(function(){
    $("#feedbackup").click(function(){
        $("#feedback").slideToggle("slow");
    });
    });
    $(document).ready(function(){
        $("#contactup").click(function(){
            $("#contact").slideToggle("slow");
        });
        });
    
